### ISSUE TITLE
CI: "more warnings and errors" should *really* do release builds

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1225]
We have two CI jobs that enable extra C++ warnings. To increase the precision of those warnings, [we enable compiler optimizations](https://github.com/newsboat/newsboat/blob/32418bf8b191f0f5aa8a62c34a798877fa652405/.cirrus.yml#L194). However, [the build logs](https://cirrus-ci.com/task/6506546056134656?command=build#L11) clearly show that we still pass `-O0 -fprofile-arcs -ftest-coverage`, i.e. we're doing *debug* builds!

This is most likely just how build matrix works in Cirrus: [the more general environment](https://github.com/newsboat/newsboat/blob/32418bf8b191f0f5aa8a62c34a798877fa652405/.cirrus.yml#L307) overrides the more specific. But we should look into that.

- [ ] does Cirrus CI document this behaviour?
- [ ] ask Cirrus support if that's their intent, since it's counter-intuitive
- [ ] depending on what we learn from docs and support, fix this so all builds except these two still run in debug mode

**Comment by Minoru** [comment]
I'd work on this myself, but I'm busy integrating cxx crate. After that I need to finish #1203, and then get back to #631. 

So yeah, this issue is a good opportunity for someone to learn about our CI a bit, if anybody is so inclined.
