### ISSUE TITLE
Try LLVM code coverage instrumentation

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1311]
grcov, the tool we use to gather code coverage metrics, [got support](https://github.com/mozilla/grcov/issues/509#issuecomment-732817023) for new LLVM machinery in version 0.6.0. This new instrumentation ostensibly provides better accuracy than the gcov format. I think we should try it for our Coveralls job.

TODO:
- [ ] try it out locally. Take inspiration from [our Coveralls job](https://github.com/newsboat/newsboat/blob/6ed5d2de55684d566c4ff7e27c7a4e55a2ffadef/.travis.yml), but take [there instructions](https://github.com/mozilla/grcov/issues/509#issuecomment-732817023) into account. Note that Clang might need some extra flags to enable this new instrumentation as well.

    We have a script in test/generate_test_coverage.sh which uses `lcov`, might be useful too.

- [ ] wait for #1305 to get merged
- [ ] update .github/workflows/coveralls.yaml to use the new instrumentation
- [ ] submit a PR :)

I don't think this is a good issue for a newcomer, but if you already compiled Newsboat a couple times, you probably have most of the tooling required to accomplish this.

**Comment by nick-cd** [comment]
Hey @Minoru! May I help with this issue?

**Comment by Minoru** [comment]
Sure! Hopefully the TODO list above is clear enough — I can't detail it any further since I didn't try that new instrumentation myself yet. Do drop a comment here if you get stuck with something, I'll try to help.

**Comment by Minoru** [comment]
Oh, by the way, for local testing, take a look at test/generate_coverage_report.sh. It generates an HTML report that you can view locally. grcov is a replacement for gcov, so you can start by updating the script to use grcov. Once that's working, you can move on to new instrumentation and see how that changes the HTML report. Once you're satisfied with the results, you can then work on moving all those findings to the CI.

**Comment by Minoru** [comment]
Hey @nick-cd, how is it going? Not trying to hurry you up or anything, just want to make sure that you aren't stuck on something that's easily resolvable.

**Comment by nick-cd** [comment]
Hey sorry, yeah I am stuck :disappointed:. I'm trying to get the LLVM toolchain to work locally, but I just can't seem to do it.
I used the `update-alternatives` program to change to clang++ but it still defaults to g++. When I manually add `CXX=clang` to the make command and change the code coverage options (`-fprofile-instr-generate -fcoverage-mapping`) it results in gcov linker errors. This confuses me because I'm no longer compiling the options that use gcov (`-fprofile-arcs -ftest-coverage` are not present in the compilation process).

That said, I do seem to have it working on the CI though. I've been playing around with the CI in a cloned repository on my account (which you can see in [this PR](https://github.com/nick-cd/ignore-me/pull/3)).

**Comment by Minoru** [comment]
Hey, that's still progress! With your PR, this issue is much further than where it was four days ago.

> I used the update-alternatives program to change to clang++ but it still defaults to g++.

Looks like [Make defaults `CXX` to `g++`](https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html), so `CXX?=c++` in our Makefile does nothing. Interesting! I'll file an issue to investigate that sometime, thanks!

> When I manually add CXX=clang to the make command and change the code coverage options (-fprofile-instr-generate -fcoverage-mapping) it results in gcov linker errors.

Note that our Makefile is not very intelligent, and it won't rebuild stuff when options (or the compiler) change. You have to run `make distclean` to remove all the build artifacts and start anew.

Another reason might be `-Zprofile` passed to Rust. I think this produces gcov output, so perhaps it embeds gcov function calls that need a gcov library?

Overall, calculating the coverage locally is more of a convenience thing. It's the CI job that we actually need.

> It's a little rough around the edges, but I think I have the right idea.

Yup! I wonder what made the coverage drop so much, though. Coveralls doesn't display file reports now — if I click on a filename, it says "source not available". Do you have any ideas on how to fix that? Once we can see the source, it'd be easier to tell if those -3% are a real deal, or a problem in need of fixing.

**Comment by Minoru** [comment]
This issue is up for grabs again. In #1474, @nick-cd managed to get Rust coverage working, so do copy that. The current obstacle (as I see it) is to collect *both* Rust and C++ coverage. `grcov` apparently requires all binaries to reside in the same directory, that's what is causing the trouble (Rust binaries are in target/, C++ one is in test/). Please see the discussion in #1474 for more details.

**Comment by Minoru** [comment]
This new approach to code coverage [was stabilized in Rust 1.60](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#source-based-code-coverage), so perhaps it's easier to implement these days?

**Comment by Minoru** [comment]
https://crates.io/crates/cargo-llvm-cov seem to automate all the setup -- perhaps try that? (via https://github.com/rust-lang/rust/issues/76085#issuecomment-1859227651)
