### ISSUE TITLE
Decompose `controller`

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#213]
`controller` does too much stuff. I already split out some of it into `CLIArgsParser` and `ConfigPaths`, but much more can be done. I went through `controller`'s public methods, and here are the sets of responsibilities I could identify:

* related to urls file:
    * [x] imports from OPML (private `import_opml()`) (#291 `OPML`)
    * [ ] ([needs reconsidering](https://github.com/newsboat/newsboat/issues/213#issuecomment-425662515)) reloads urls file (`reload_urls_file()`)
    * [ ] ([needs reconsidering](https://github.com/newsboat/newsboat/issues/213#issuecomment-425662515)) opens editor with urls file (`edit_urls_file()`)

* related to items:
    * [x] marks item deleted (`mark_deleted()`) (#266 removed entirely in favour of `cache::mark_item_deleted()`)
    * [x] writes item into plain-text file (`write_item()`), possibly a temporary one (`write_temporary_item()`) (#311 mostly moved to `ItemRenderer`)
    * [ ] ([needs reconsidering](https://github.com/newsboat/newsboat/issues/213#issuecomment-429973061)) updates flags on an item (`update_flags()`)

* related to config:
    * [x] dumps configfile into a file (`dump_config()`) ([will stay in `Controller`](https://github.com/newsboat/newsboat/issues/213#issuecomment-429982026))
    * [ ] ([needs reconsidering](https://github.com/newsboat/newsboat/issues/213#issuecomment-429981281)) reloads config (`load_configfile()`, `update_config()`)

* related to feeds:
    - [x] returns feeds by their index (TODO: in what list?) or feedurl (get_feed(), get_feed_by_url()) (#216 `FeedContainer`)
    - [x] manages feedlist and visible feeds list (#216 `FeedContainer`)
    - [x] returns position of next unread feed (get_pos_of_next_unread()) (#216 `FeedContainer`)
    - [x] returns list of feeds (possibly to someone who already holds some lock -- TODO: which one? Apparently feeds_mutex) (get_all_feeds(), get_all_feeds_unlocked()) (#216 `FeedContainer`)
    - [x] sorts feeds according to feed-sort-order (sort_feeds()) (#216 `FeedContainer`)
    - [x] counts feeds per tag (get_feed_count_per_tag()) (#216 `FeedContainer`)
    - [x] reloading feeds (`reload()`, `reload_all()`, `reload_indexes()`, `reload_range()`, `start_reaload_all_thread()`) (#253 `Reloader`)
    - [x] export to OPML (private `export_to_opml()`, `rec_find_rss_outlines()`) (#291 `OPML`)
    - [ ] ([needs reconsidering](https://github.com/newsboat/newsboat/issues/213#issuecomment-431607489)) marks all feeds, some article, or a whole feed read (`mark_all_read()`, `mark_article_read()`, `mark_all_read()`)

* miscellaneous:
    * [x] prints version and usage info (#244 moved to `newsboat.cpp`)
    * [x] storing if CTRL-C has been pressed (`ctrl_c_hit`) (#271 moved to `view`)
    * [x] runs a bookmark script (`bookmark()`) (#271 moved to `formaction`)
    * [x] sends notifications through notify-program (`notify()`) (#272 moved to `Reloader`)
    * [x] manages a pointer to configstore (`get_cfg()`) (#302)
    * [x] manages a pointer to cache (`get_cache()`) (#300)
    * [ ] manages a list of filters
        - [x] `get_filters()` (#304)
        - [ ] ([needs reconsidering](https://github.com/newsboat/newsboat/issues/213#issuecomment-430010405)) `filters`
    * [ ] ([cancelled](https://github.com/newsboat/newsboat/issues/213#issuecomment-433700539) storing current `view` (`v`, `get_view()`, `set_view()`)
    * [ ] ([@Minoru gave up](https://github.com/newsboat/newsboat/issues/213#issuecomment-433701584)) running the app (`run()`)
    * [x] puts a url into queue (`enqueue_url()`) (#350)

It's quite possible that each responsibility area could be split into an object, and `controller` would be just a composition of those objects.

It's also quite possible that some of these methods shouldn't even exist, and can be eliminated by refactorings to APIs of other classes.

If someone wants to take a bash at some of these areas, just write a comment. Also, if my experience with `CLIArgsParser` and `ConfigPaths` is representative, I'm probably wrong about some of these methods, and they should belong to some other area than the one I listed—if so, please point that out.

**Comment by kmws** [comment]
I will probably take a deeper look at this, since I wanted to do it anyway sometime. My first thought about controller was that it does too much.

**Comment by Minoru** [comment]
Cool!

One thing I should've stated in the issue is: the goal of this refactoring is to extract existing code into a separate unit, and put it under tests. Resist the urge to fix little things and improve interfaces "while you're at it". Feel free to open issues as you go, so you could come back to problematic places later.

I understand that writing tests might be less enjoyable that writing "actual code", so once you've done the extraction, open a PR. We'll mark it as WIP, and I'll write half the tests to help you. I don't want to merge such a PR without tests because I need some assurance that nothing got broken in the process. And if you could write some tests *before* the extraction, that would be just fantastic!

**Comment by kmws** [comment]
>Resist the urge to fix little things and improve interfaces "while you're at it". 
Yes, I also think that the first step should be to lock down the code in order to decouple it a little bit, then to refactor.

 It's tough, though. :)

>I need some assurance that nothing got broken in the process
That's the most the most important thing I guess.

**Comment by Minoru** [comment]
I'm slo-o-o-owly factoring out reloading functions.

**Comment by Minoru** [comment]
I'm working on OPML stuff.

**Comment by Minoru** [comment]
We're past the midpoint, with 14 out of 26 functions already refactored, and controller.cpp slimming from 1866 lines to 1051. Let's keep the momentum and finish this for the December release!

**Comment by Minoru** [comment]
I no longer believe that `edit_urls_file()` and `reload_urls_file()` should be extracted into separate classes. They don't keep a state of their own, and all they do fits into a single method. Basically, they're just too small to be bothered with.

I'll re-evaluate that before closing the issue.

**Comment by Minoru** [comment]
I'm working on `write_item()` and `write_temporary_item()`.

**Comment by Minoru** [comment]
I'm done with `update_flags()`. I don't see a reason to move it out of `Controller`: this method doesn't do anything by itself, it just calls out to remote API and RssItem methods.

I'll re-evaluate that before closing the issue.

**Comment by Minoru** [comment]
I'm working on `load_configfile()` and `update_config()`.

**Comment by kmws** [comment]
>dump_config() simply calls dump_config() method of every object that Controller owns (...)

Yes, that is why now the Controller can't get rid of `filters` at the moment. I don't know how to resolve it at the moment.

**Comment by Minoru** [comment]
After a long, long look at mark-all-read functions, I still can't see where they really belong. They contain quite a chunk of logic, so should be moved out; but they talk to remote APIs, `Cache` and `RssFeed`s, so need access to stuff `Controller` contains.

Will revisit before closing the issue.

**Comment by Minoru** [comment]
I give up on `run()` for now. There are places that could be moved into methods, but it won't improve things much: these methods will still depend on everything else. That would be more like chopping the method than refactoring it.

**Comment by Minoru** [comment]
Working on `enqueue_url`.

**Comment by Minoru** [comment]
All right! controller.cpp slimmed from 1866 to 909 lines—very nice! We couldn't refactor some of the functions, but I think we'll get back to them eventually.

Thanks for all the work, @kmws!
